In [5]:
import pandas as pd 
print("A biblioteca pandas foi importada com sucesso!")

A biblioteca pandas foi importada com sucesso!

In [11]:
#Ler o arquivo CSV

df = pd.read_csv('../data/raw/installments_payments.csv')
print("O arquivo CSV foi lido com sucesso!")
print(f"O DataFrame tem {df.shape[0]} linhas e {df.shape[1]} colunas.")

O arquivo CSV foi lido com sucesso!
O DataFrame tem 13605401 linhas e 8 colunas.

In [12]:
df.head()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585

In [13]:
df.shape

(13605401, 8)

In [9]:
df.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'NUM_INSTALMENT_VERSION',
       'NUM_INSTALMENT_NUMBER', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT',
       'AMT_INSTALMENT', 'AMT_PAYMENT'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SK_ID_PREV              1000 non-null   int64
 1   SK_ID_CURR              1000 non-null   int64
 2   NUM_INSTALMENT_VERSION  1000 non-null   float64
 3   NUM_INSTALMENT_NUMBER   1000 non-null   int64
 4   DAYS_INSTALMENT         1000 non-null   float64
 5   DAYS_ENTRY_PAYMENT      1000 non-null   float64
 6   AMT_INSTALMENT          1000 non-null   float64
 7   AMT_PAYMENT             1000 non-null   float64
dtypes: float64(5), int64(3)
memory usage: 62.6 KB

In [ ]:
# Primeira regra de negócio: Média de Atraso
df['DAYS_DELAY'] = (
    df['DAYS_ENTRY_PAYMENT'] - df['DAYS_INSTALMENT']
)

df[['DAYS_INSTALMENT', 
    'DAYS_ENTRY_PAYMENT',
    'DAYS_DELAY']].head()

   DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  DAYS_DELAY
0          -1180.0             -1187.0        -7.0
1          -2156.0             -2156.0         0.0
2            -63.0               -63.0         0.0
3          -2418.0             -2426.0        -8.0
4          -1383.0             -1366.0        17.0

In [17]:
df['DAYS_DELAY'] = (
    df['DAYS_ENTRY_PAYMENT']
    - df['DAYS_INSTALMENT']
)

df['DAYS_DELAY'].describe()

count    1.360250e+07
mean    -8.787405e+00
std      2.553990e+01
min     -3.189000e+03
25%     -1.400000e+01
50%     -6.000000e+00
75%      0.000000e+00
max      2.884000e+03
Name: DAYS_DELAY, dtype: float64

In [33]:
df['DAYS_DELAY'].value_counts().head(20)

DAYS_DELAY
 0.0     3146350
-1.0      525380
-2.0      507963
-3.0      459365
-9.0      454549
-4.0      452509
-8.0      447453
-6.0      442527
-7.0      438668
-5.0      438267
-10.0     426481
-11.0     402474
-12.0     364528
-13.0     332190
-14.0     295531
-15.0     267534
 1.0      266096
-16.0     243808
-17.0     225429
-19.0     217453
Name: count, dtype: int64

In [34]:
df['DAYS_DELAY'].value_counts().sort_index()

DAYS_DELAY
-3189.0    1
-1681.0    1
-1640.0    1
-1600.0    1
-1335.0    1
          ..
 2847.0    1
 2852.0    2
 2871.0    1
 2882.0    1
 2884.0    1
Name: count, Length: 2404, dtype: int64

In [35]:
(df['DAYS_DELAY'] > 0).mean()

np.float64(0.08428042657471103)